version: '3.9'
services:
  wordpress:
    container_name: wordpress-web
    image: wordpress:latest
    depends_on:
      - db
    restart: always
    links:
      - db:mysql
    networks:
      docker-net1:
        ipv4_address: 192.168.2.243
    ports:
      - "8880:80"
    working_dir: /var/www/html
    volumes:
      - wp-data:/var/www/html/
#      - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wordpress

  db:
    container_name: wordpress-db
    image: mysql:5.7
    restart: always
    networks:
      docker-net1:
        ipv4_address: 192.168.2.244
    volumes:
      - wp-mysql-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

#    env_file: .env
#    environment:
#      - WORDPRESS_DB_HOST=db:3306
#      - WORDPRESS_DB_USER=$MYSQL_USER9
#      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
#      - WORDPRESS_DB_NAME=wordpress

#  webserver:
#    depends_on:
#      - wordpress
#    image: nginx:1.15.12-alpine
#    container_name: webserver
#    restart: unless-stopped
#    ports:
#      - "80:80"  
#      - "443:443"
#    volumes:
#      - wordpress:/var/www/html
#      - /path/to/repo/nginx-conf-folder/:/etc/nginx/conf.d

volumes:
  wp-data:
    external: true
  wp-mysql-data:
    external: true

networks:
  default:
    external:
      name: docker-net1
  docker-net1:
    external: true
